- platform: mqtt
  state_topic: "office/motion"
  name: "Presence"
  qos: 1
  payload_on: "True"
  payload_off: "False"
  sensor_class: motion
- platform: nest
  monitored_conditions:
    - 'is_using_emergency_heat'
    - 'has_leaf'
    - 'online'
