
homeassistant:
  name: Home
  latitude: 49.018742
  longitude: 21.221933
  elevation: 365
  unit_system: metric
  time_zone: Europe/Bratislava
  customize: !include_dir_merge_named customized

group: !include groups.yaml

http:
  api_password: !secret http_password

frontend:

discovery:

updater:

conversation:

history:

logbook:

sun:

mqtt: !include mqtt.yaml

sensor: !include sensor.yaml

nest: !include nest.yaml

climate: !include climate.yaml

binary_sensor: !include binary_sensor.yaml

device_tracker: !include device_tracker.yaml

camera: !include outside_camera.yaml

media_player: !include media_player.yaml

mysensors: !include mysensors.yaml
